-- MySQL Script generated by MySQL Workbench
-- 08/22/16 16:49:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Laboratorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Laboratorio` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema articulos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema articulos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `articulos` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
USE `Laboratorio` ;

-- -----------------------------------------------------
-- Table `Laboratorio`.`caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`caracteristicas` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`caracteristicas` (
  `idcaracteristicas` INT NOT NULL AUTO_INCREMENT,
  `fechaR` DATETIME NOT NULL,
  `observ` TEXT(45) NOT NULL,
  `resguardo` VARCHAR(45) NOT NULL,
  `protocolo` VARCHAR(45) NOT NULL,
  `almacen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcaracteristicas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`Tiempo` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`Tiempo` (
  `idTiempo` INT NOT NULL AUTO_INCREMENT,
  `edad` VARCHAR(45) NOT NULL,
  `tiempoV` DATETIME NOT NULL,
  PRIMARY KEY (`idTiempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`paciente` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `appaterno` VARCHAR(45) NOT NULL,
  `apmaterno` VARCHAR(45) NOT NULL,
  `nacimiento` DATETIME NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `Tiempo_idTiempo` INT NOT NULL,
  PRIMARY KEY (`idpaciente`),
  CONSTRAINT `fk_paciente_Tiempo1`
    FOREIGN KEY (`Tiempo_idTiempo`)
    REFERENCES `Laboratorio`.`Tiempo` (`idTiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_paciente_Tiempo1_idx` ON `Laboratorio`.`paciente` (`Tiempo_idTiempo` ASC);


-- -----------------------------------------------------
-- Table `Laboratorio`.`muestra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`muestra` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`muestra` (
  `idmuestra` INT NOT NULL AUTO_INCREMENT,
  `muestra` VARCHAR(45) NOT NULL,
  `contenedor` VARCHAR(45) NOT NULL,
  `umedida` FLOAT NOT NULL,
  `sufijo` VARCHAR(10) NOT NULL,
  `total` DECIMAL NOT NULL,
  `caracteristicas_idcaracteristicas` INT NOT NULL,
  PRIMARY KEY (`idmuestra`),
  CONSTRAINT `fk_muestra_caracteristicas1`
    FOREIGN KEY (`caracteristicas_idcaracteristicas`)
    REFERENCES `Laboratorio`.`caracteristicas` (`idcaracteristicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_muestra_caracteristicas1_idx` ON `Laboratorio`.`muestra` (`caracteristicas_idcaracteristicas` ASC);


-- -----------------------------------------------------
-- Table `Laboratorio`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`medico` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nombreMD` VARCHAR(45) NOT NULL,
  `appaternoMD` VARCHAR(45) NOT NULL,
  `apmaternoMD` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ucs2;


-- -----------------------------------------------------
-- Table `Laboratorio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apaterno` VARCHAR(45) NOT NULL,
  `apmaterno` VARCHAR(45) NOT NULL,
  `matricula` DECIMAL(15) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorio`.`rusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`rusuario` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`rusuario` (
  `id_rusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `rpass` VARCHAR(45) NOT NULL,
  `alta` DATETIME NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `tel` DECIMAL(15) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`id_rusuario`),
  CONSTRAINT `fk_rusuario_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `Laboratorio`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_rusuario_usuario_idx` ON `Laboratorio`.`rusuario` (`usuario_idusuario` ASC);


-- -----------------------------------------------------
-- Table `Laboratorio`.`archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`archivos` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`archivos` (
  `idarchivos` INT NOT NULL AUTO_INCREMENT,
  `archivo_binario` BLOB NOT NULL,
  `archivo_nombre` VARCHAR(255) NOT NULL,
  `archivo_peso` VARCHAR(15) NOT NULL,
  `archivo_tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idarchivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Hclinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`Hclinica` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`Hclinica` (
  `idHclinica` INT NOT NULL AUTO_INCREMENT,
  `medico_idmedico` INT NOT NULL,
  `paciente_idpaciente` INT NOT NULL,
  `archivos_idarchivos` INT NOT NULL,
  PRIMARY KEY (`idHclinica`),
  CONSTRAINT `fk_Hclinica_medico1`
    FOREIGN KEY (`medico_idmedico`)
    REFERENCES `Laboratorio`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hclinica_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `Laboratorio`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hclinica_archivos1`
    FOREIGN KEY (`archivos_idarchivos`)
    REFERENCES `Laboratorio`.`archivos` (`idarchivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ucs2;

CREATE INDEX `fk_Hclinica_medico1_idx` ON `Laboratorio`.`Hclinica` (`medico_idmedico` ASC);

CREATE INDEX `fk_Hclinica_paciente1_idx` ON `Laboratorio`.`Hclinica` (`paciente_idpaciente` ASC);

CREATE INDEX `fk_Hclinica_archivos1_idx` ON `Laboratorio`.`Hclinica` (`archivos_idarchivos` ASC);


-- -----------------------------------------------------
-- Table `Laboratorio`.`muestra_proc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`muestra_proc` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`muestra_proc` (
  `idmuestra_proc` INT NOT NULL AUTO_INCREMENT,
  `ensayo` VARCHAR(45) NOT NULL,
  `resultado` VARCHAR(45) NOT NULL,
  `observ` TEXT(45) NOT NULL,
  `fechaP` DATETIME NOT NULL,
  PRIMARY KEY (`idmuestra_proc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Laboratorio`.`quimico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`quimico` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`quimico` (
  `idquimico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `appaterno` VARCHAR(45) NOT NULL,
  `apmaterno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idquimico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`registroDos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`registroDos` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`registroDos` (
  `idregistroDos` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(45) NOT NULL,
  `protocolo` VARCHAR(45) NOT NULL,
  `tipomuestra` VARCHAR(45) NOT NULL,
  `fechaI` TIMESTAMP NOT NULL,
  `muestra_proc_idmuestra_proc` INT NOT NULL,
  `quimico_idquimico` INT NOT NULL,
  PRIMARY KEY (`idregistroDos`),
  CONSTRAINT `fk_registroDos_muestra_proc1`
    FOREIGN KEY (`muestra_proc_idmuestra_proc`)
    REFERENCES `Laboratorio`.`muestra_proc` (`idmuestra_proc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroDos_quimico1`
    FOREIGN KEY (`quimico_idquimico`)
    REFERENCES `Laboratorio`.`quimico` (`idquimico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_registroDos_muestra_proc1_idx` ON `Laboratorio`.`registroDos` (`muestra_proc_idmuestra_proc` ASC);

CREATE INDEX `fk_registroDos_quimico1_idx` ON `Laboratorio`.`registroDos` (`quimico_idquimico` ASC);


-- -----------------------------------------------------
-- Table `Laboratorio`.`Responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`Responsable` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`Responsable` (
  `idResponsable` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `appaterno` VARCHAR(45) NOT NULL,
  `apmaterno` VARCHAR(45) NOT NULL,
  `fecha` TIME NOT NULL,
  `hora` DATE NOT NULL,
  PRIMARY KEY (`idResponsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`codigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Laboratorio`.`codigo` ;

CREATE TABLE IF NOT EXISTS `Laboratorio`.`codigo` (
  `idcodigo` INT NOT NULL AUTO_INCREMENT,
  `codigo` DECIMAL NOT NULL,
  `Generar` BLOB(25) NOT NULL,
  `Responsable_idResponsable` INT NOT NULL,
  `muestra_idmuestra` INT NOT NULL,
  PRIMARY KEY (`idcodigo`),
  CONSTRAINT `fk_codigo_Responsable1`
    FOREIGN KEY (`Responsable_idResponsable`)
    REFERENCES `Laboratorio`.`Responsable` (`idResponsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_muestra1`
    FOREIGN KEY (`muestra_idmuestra`)
    REFERENCES `Laboratorio`.`muestra` (`idmuestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_codigo_Responsable1_idx` ON `Laboratorio`.`codigo` (`Responsable_idResponsable` ASC);

CREATE INDEX `fk_codigo_muestra1_idx` ON `Laboratorio`.`codigo` (`muestra_idmuestra` ASC);

USE `articulos` ;

-- -----------------------------------------------------
-- Table `articulos`.`zapatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articulos`.`zapatos` ;

CREATE TABLE IF NOT EXISTS `articulos`.`zapatos` (
  `id_zapato` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `numero` INT(10) NOT NULL,
  `precio` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `color` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_zapato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
